"""empty message

Revision ID: 778eb626a992
Revises: 8c651f514964
Create Date: 2020-05-14 12:39:08.544875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778eb626a992'
down_revision = '8c651f514964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weibo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weibo')
    # ### end Alembic commands ###
